name: build and deploy

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repo
      uses: actions/checkout@master

    - name: Install Node
      uses: actions/setup-node@master
      with:
        node-version: '13.x'

    - name: Install Dependencies
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install

    - name: Build Website
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build

    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: build
        path: build

  deploy-main:

    runs-on: ubuntu-latest

    needs: build

    steps:

      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build

      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:connect420
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}